name: Detect CI Trigger
description: |
  Detect keywords used to control the CI in the subject line of a commit message
inputs:
  keywords:
    description: |
      The keywords to detect. Currently, only a single keyword is supported.
    required: true
outputs:
  trigger-found:
    description: |
      true if any of the keywords has been found in the subject line of the commit
      message
    value: ${{ steps.detect-trigger.outputs.CI_TRIGGERED }}
runs:
  using: "composite"
  steps:
    - name: determine the commit hash
      id: commit_ref
      run: |
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo '::set-output name=REF::HEAD^2'
        else
          echo '::set-output name=REF::HEAD'
        fi
      shell: bash
    - name: fetch a sufficient number of commits
      run: git fetch --depth 2
      shell: bash
    - name: show commit message
      run: |
        echo -n "commit message: '"
        git log -n 1 --pretty=format:%s ${{ steps.commit_ref.outputs.REF }}
        echo "'"
        echo "searching for '${{ inputs.keywords }}'"
      shell: bash
    - name: detect trigger
      id: detect_trigger
      run: $GITHUB_ACTION_PATH/script.sh ${{ steps.commit_ref.outputs.REF }} ${{ inputs.keywords }}
      shell: bash
    - name: show detection result
      run: |
        echo "trigger detected: ${{ steps.detect_trigger.outputs.CI_TRIGGERED }}"
      shell: bash
