name: Detect CI Trigger
description: |
  Detect keywords used to control the CI in the subject line of a commit message
inputs:
  keywords:
    description: |
      The keywords to detect. Currently, only a single keyword is supported.
    required: true
outputs:
  trigger-found:
    description: |
      true if any of the keywords has been found in the subject line of the commit
      message
    value: ${{ steps.detect-trigger.outputs.CI_TRIGGERED }}
runs:
  using: "composite"
  steps:
    - name: fetch a sufficient number of commits
      run: git fetch --depth 2
      shell: bash
    - name: detect trigger
      id: detect-trigger
      run: |
        bash $GITHUB_ACTION_PATH/script.sh ${{ github.event_name }} ${{ inputs.keywords }}
      shell: bash
    - name: show detection result
      run: |
        echo "trigger detected: ${{ steps.detect-trigger.outputs.CI_TRIGGERED }}"
      shell: bash
